### ISSUE TITLE
should the gene expression matrix be normalised?

### ISSUE THREAD

**Issue by helianthuszhu** [aertslab/AUCell#15]
Hi,
   Thanks for providing this wonderful tools. I am just wondering what format of the inputted gene expression would be better, raw count, or normalised one, such as log2(count+1), log2(TPM+1).

Thank you very much.

Best,
Xiaoqiang

**Comment by s-aibar** [comment]
It doesn't really matter much. The AUC score is calculated for each cell individually.

**Comment by lucygarner** [comment]
@s-aibar, I have just put a related question in pySCENIC.  Specifically, I am wondering about activation datasets where the composition of the RNA will vary greatly between the activated cells and the unstimulated cells.  In this case, the rankings of non-activation-associated genes would be reduced in the activated cells, due to the upregulation of a whole host of other genes, however their absolute expression might not actually decrease.  I am seeing a lot of downregulated TF regulons in my dataset, and I am wondering whether some of these might be an artifact of this effect?
